apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1
  
  vpc:
  id: "vpc-0937c7ba7ea9d4728"  # (optional, must match VPC ID used for each subnet below)
       
   
managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: m5.large
  
    # your K8 node can be anytime taken back by AWS
    spot: true
    availabilityZones:
    - us-east-1a
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes # replace this with your keypair exists in AWS.
