apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1
  
  vpc:
  id: "vpc-0937c7ba7ea9d4728"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      us-east-1a:
        id: "subnet-0813ea25adf7b2d62"
        cidr: "10.0.0.0/20" # (optional, must match CIDR used by the given subnet)

      us-east-1b:
        id: "subnet-04d2bdec0aaf3a43d"
        cidr: "10.0.16.0/20"  # (optional, must match CIDR used by the given subnet)
    
      
managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: m5.large
  
    # your K8 node can be anytime taken back by AWS
    spot: true
    availabilityZones:
    - us-east-1a
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes # replace this with your keypair exists in AWS.
